name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  uno: ^1.1.12
  result_dart: ^2.1.0
  shelf: ^1.4.2
  shelf_modular: ^2.1.0
  postgresql2: ^1.7.0
  redis: ^4.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
